### When running ```python3 -m PyFileName.py```  
i get an error message that says:  
/usr/bin/python3: Error while finding module specification for 'myPy.py' (AttributeError: module 'myPy' has no attribute '__path__')  
**Solution found at**:  
>> https://stackoverflow.com/questions/36230492/error-while-finding-spec-for-fibo-py-class-attributeerror-module-object  

